### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Matt-MX** [Matt-MX/ServerGUI#13]
ServerGUI will be redesigned in a new scalable way.

```yaml
somegui:
	title: "Main GUI"
	rows: 6
	items:
		0:
			material: COMPASS
			# Leads to another gui named 'lobbies'
			opens: lobbies
	[...]
lobbies:
	title: "Lobbies"
	rows: 6
	items:
		0:
			material: COMPASS
			server: lobby1
```

Allowing for sub-categories of servers to connect to, which should help to make the plugin more viable for other servers.
The new plugin will come with a neat API to help with more any developers' more specific needs.

Will be working on this soon!
